name: ftg-mod-push
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: "ℹ️ Новый *push* от: ${{github.actor}}.\n*Репозиторий: *${{github.repository}}\n*Сообщение: *${{github.event.head_commit.message}}\n----\n*Дополнительная информация: *[по ссылке](https://github.com/${{github.repository}}/commits/master)\n"


name: ftg-mod-pr
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: "🔗 Новый *pull-request* от: ${{github.actor}}.\n*Репозиторий: *${{github.repository}}\n*Сообщение: *${{github.event.head_commit.message}}\n----\n*Дополнительная информация: *[по ссылке](https://github.com/${{github.repository}}/pulls)\n"

name: ftg-mod-prr
on: [pull_request_review]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: "🗒️ Новый *pull-request review* от: ${{github.actor}}.\n*Репозиторий: *${{github.repository}}\n*Сообщение: *${{github.event.head_commit.message}}\n----\n*Дополнительная информация: *[по ссылке](https://github.com/${{github.repository}}/pulls)\n"

name: ftg-mod-prrc
on: [pull_request_review_comment]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: "📝 Новый комментарий к *pull-request review* от: ${{github.actor}}.\n*Репозиторий: *${{github.repository}}\n*Сообщение: *${{github.event.head_commit.message}}\n----\n*Дополнительная информация: *[по ссылке](https://github.com/${{github.repository}}/pulls)\n"

name: ftg-mod-fork
on: [fork]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: "❕ Новый *fork* от: ${{github.actor}}.\n*Репозиторий: *${{github.repository}}\n*Сообщение: *${{github.event.head_commit.message}}\n----\n*Дополнительная информация: *[по ссылке](https://github.com/${{github.repository}}/network/members)\n"

name: ftg-mod-issue
on: [issues]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: "⁉️ Новый *issue* от: ${{github.actor}}.\n*Репозиторий: *${{github.repository}}\n*Сообщение: *${{github.event.head_commit.message}}\n----\n*Дополнительная информация: *[по ссылке](https://github.com/${{github.repository}}/issues)\n"